### PR TITLE
Properly format chained messages

### PR DESCRIPTION
**Pull request by ska-kialo**
I noticed a problem with error messages appearing as `[object Object]` in the Jenkins report.
The issue is that the `messageText` property of a typescript `Diagnostic` object can either be a string or an object containing a message and an optional list of further messages.

This fixes this. I still need to write a test but I thought I'd create this PR for some first feedback.

### CODE REVIEW

**Comment by nicolas-schmitt** [comment]
Hi, sorry for the delay and thank you very much for the input.
Did have time to take care of the tests or should i do it ?

**Comment by ska-kialo** [comment]
Hi, no worries. I actually forgot about it as well, but if you want I can take care of the test cases.
*Edit:* Actually, I'll add them, since there seems to be an error in my code

**Comment by ska-kialo** [comment]
@nicolas-schmitt Added tests and fixed the implementation :)

**Edit:** I got confused between typescript versions, I'll need to fix again

**Comment by ska-kialo** [comment]
Okay, that should do it.

**Comment by ska-kialo** [comment]
(I'll close this because I accidentally pushed to the wrong branch)

**Pull request closed without merging**
